version: 2

project_name: refind-btrfs-snapshots

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go vet ./...
    - go test -race ./...
    - gofmt -s -w .
    - go mod verify

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X 'github.com/jmylchreest/refind-btrfs-snapshots/cmd.Version={{.Version}}'
      - -X 'github.com/jmylchreest/refind-btrfs-snapshots/cmd.Commit={{.Commit}}'
      - -X 'github.com/jmylchreest/refind-btrfs-snapshots/cmd.BuildTime={{.Date}}'

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - "^perf:"
      - "^build:"
# Commented out - uncomment when ready to publish
# brews:
#   - repository:
#       owner: jmylchreest
#       name: homebrew-tools
#     directory: Formula
#     homepage: "https://github.com/jmylchreest/refind-btrfs-snapshots"
#     description: "Generate rEFInd boot entries for btrfs snapshots"
#     license: "GPL-3.0"
#     test: |
#       system "#{bin}/refind-btrfs-snapshots version"
#     dependencies:
#       - name: coreutils
#         type: optional
#     install: |
#       bin.install "refind-btrfs-snapshots"
#       etc.install "configs/refind-btrfs-snapshots.yaml" => "refind-btrfs-snapshots.conf"
#       # Note: Using system inotify (launchd) instead of brew services for file watching
#       (prefix/"systemd").install "systemd/refind-btrfs-snapshots.service"
#       (prefix/"systemd").install "systemd/refind-btrfs-snapshots.path"

aurs:
  - name: refind-btrfs-snapshots-bin
    homepage: "https://github.com/jmylchreest/refind-btrfs-snapshots"
    description: "Generate rEFInd boot entries for btrfs snapshots"
    maintainers:
      - "John Mylchreest <jmylchreest at gmail dot com>"
    license: "GPL3"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/refind-btrfs-snapshots-bin.git"
    depends:
      - btrfs-progs
      - util-linux
    backup:
      - etc/refind-btrfs-snapshots.conf
    package: |-
      # binaries
      install -Dm755 ./refind-btrfs-snapshots "${pkgdir}/usr/bin/refind-btrfs-snapshots"

      # configuration
      install -Dm644 ./configs/refind-btrfs-snapshots.yaml "${pkgdir}/etc/refind-btrfs-snapshots.conf"

      # systemd units
      install -Dm644 ./systemd/refind-btrfs-snapshots.service "${pkgdir}/usr/lib/systemd/system/refind-btrfs-snapshots.service"
      install -Dm644 ./systemd/refind-btrfs-snapshots.path "${pkgdir}/usr/lib/systemd/system/refind-btrfs-snapshots.path"
